//! Core readline configuration

use std::{
    borrow::BorrowMut,
    io::{Read, Seek, Write},
};

use ::crossterm::{
    event::{
        read, DisableBracketedPaste, EnableBracketedPaste, Event, KeyCode, KeyEvent, KeyModifiers,
    },
    execute,
    style::{Color, ContentStyle},
    terminal::{disable_raw_mode, enable_raw_mode},
};
use shrs_utils::cursor_buffer::{CursorBuffer, Location};
use shrs_vi::{Action, Command, Motion, Parser};

use super::{painter::Painter, *};
use crate::{
    prelude::{Completer, Completion, CompletionCtx, History, ReplaceMethod, Shell, Theme},
    prompt_content_queue::PromptContentQueue,
    state::States,
};

pub trait Readline {
    fn read_line(&mut self, sh: &Shell, states: &mut States) -> String;
}

/// Operating mode of readline
#[derive(Debug, PartialEq, Eq, Clone, Copy)]
pub enum LineMode {
    /// Vi insert mode
    Insert,
    /// Vi normal mode
    Normal,
}

/// State or where the prompt is in history browse mode
#[derive(Debug, PartialEq, Eq)]
pub enum HistoryInd {
    /// Brand new prompt
    Prompt,
    /// In history line
    Line(usize),
}

impl HistoryInd {
    /// Go up (less recent) in history, if in prompt mode, then enter history
    pub fn up(&self, limit: usize) -> HistoryInd {
        match self {
            HistoryInd::Prompt => {
                if limit == 0 {
                    HistoryInd::Prompt
                } else {
                    HistoryInd::Line(0)
                }
            },
            HistoryInd::Line(i) => HistoryInd::Line((i + 1).min(limit - 1)),
        }
    }

    /// Go down (more recent) in history, if in most recent history line, enter prompt mode
    pub fn down(&self) -> HistoryInd {
        match self {
            HistoryInd::Prompt => HistoryInd::Prompt,
            HistoryInd::Line(i) => {
                if *i == 0 {
                    HistoryInd::Prompt
                } else {
                    HistoryInd::Line(i.saturating_sub(1))
                }
            },
        }
    }
}

/// State needed for readline
pub struct LineState {
    /// Cursor buffer structure for interactive editing
    pub cb: CursorBuffer,
    /// stored lines in a multiprompt command
    pub lines: String,

    // TODO this is temp, find better way to store prefix of current word
    current_word: String,
    // TODO dumping history index here for now
    history_ind: HistoryInd,
    /// Line contents that were present before entering history mode
    saved_line: String,
    /// The current mode the line is in
    mode: LineMode,
}

impl LineState {
    pub fn new() -> Self {
        LineState {
            cb: CursorBuffer::default(),
            current_word: String::new(),
            history_ind: HistoryInd::Prompt,
            saved_line: String::new(),
            mode: LineMode::Insert,
            lines: String::new(),
        }
    }

    pub fn mode(&self) -> LineMode {
        self.mode
    }

    /// Get the contents of the prompt
    pub fn get_full_command(&self) -> String {
        let mut res: String = self.lines.clone();
        let cur_line: String = self.cb.as_str().into();
        res += cur_line.as_str();

        res
    }
}

/// Configuration for readline
#[derive(Builder)]
#[builder(pattern = "owned")]
#[builder(setter(prefix = "with"))]
pub struct Line {
    /// Completion menu, see [Menu]
    #[builder(default = "Box::new(DefaultMenu::default())")]
    #[builder(setter(custom))]
    menu: Box<dyn Menu<MenuItem = Completion, PreviewItem = String>>,

    #[builder(default = "Box::new(DefaultBufferHistory::default())")]
    #[builder(setter(custom))]
    buffer_history: Box<dyn BufferHistory>,

    /// Syntax highlighter, see [Highlighter]
    #[builder(default = "Box::new(SyntaxHighlighter::default())")]
    #[builder(setter(custom))]
    highlighter: Box<dyn Highlighter>,

    /// Custom prompt, see [Prompt]
    #[builder(default = "Box::new(DefaultPrompt::default())")]
    #[builder(setter(custom))]
    prompt: Box<dyn Prompt>,

    // ignored fields
    #[builder(default = "Painter::default()")]
    #[builder(setter(skip))]
    painter: Painter,

    /// Currently pressed keys in normal mode
    #[builder(default = "String::new()")]
    #[builder(setter(skip))]
    normal_keys: String,

    #[builder(default = "Box::new(DefaultSuggester)")]
    suggester: Box<dyn Suggester>,

    /// Alias expansions, see [Abbreviations]
    #[builder(default = "Snippets::default()")]
    snippets: Snippets,
}

impl Default for Line {
    fn default() -> Self {
        LineBuilder::default().build().unwrap()
    }
}

// TODO none of the builder stuff is being autogenerated rn :()
impl LineBuilder {
    pub fn with_menu(
        mut self,
        menu: impl Menu<MenuItem = Completion, PreviewItem = String> + 'static,
    ) -> Self {
        self.menu = Some(Box::new(menu));
        self
    }
    pub fn with_highlighter(mut self, highlighter: impl Highlighter + 'static) -> Self {
        self.highlighter = Some(Box::new(highlighter));
        self
    }
    pub fn with_prompt(mut self, prompt: impl Prompt + 'static) -> Self {
        self.prompt = Some(Box::new(prompt));
        self
    }
}

impl Readline for Line {
    /// Start readline and read one line of user input
    fn read_line(&mut self, sh: &Shell, states: &mut States) -> String {
        states.insert(LineState::new());
        self.read_events(sh, states).unwrap()
    }
}

impl Line {
    fn read_events(&mut self, sh: &Shell, states: &States) -> anyhow::Result<String> {
        // ensure we are always cleaning up whenever we leave this scope
        struct CleanUp;
        impl Drop for CleanUp {
            fn drop(&mut self) {
                let _ = disable_raw_mode();
                let _ = execute!(std::io::stdout(), DisableBracketedPaste);
            }
        }
        let _cleanup = CleanUp;

        enable_raw_mode()?;
        execute!(std::io::stdout(), EnableBracketedPaste)?;

        let mut auto_run = false;
        self.painter.init().unwrap();
        if let Some(c) = states.get_mut::<PromptContentQueue>().pop() {
            auto_run = c.auto_run;
            states
                .line()
                .cb
                .insert(Location::Cursor(), c.content.as_str())?;
        }

        loop {
            let res = states.line().get_full_command();

            // syntax highlight
            let mut styled_buf = self
                .highlighter
                .highlight(states, &res)
                .slice_from(states.line().lines.len());

            // add currently selected completion to buf
            if self.menu.is_active() {
                if let Some(selection) = self.menu.current_selection() {
                    let trimmed_selection = &selection.accept()[states.line().current_word.len()..];
                    styled_buf.push(
                        trimmed_selection,
                        ContentStyle {
                            foreground_color: Some(Color::Red),
                            ..Default::default()
                        },
                    );
                }
            } else {
                // get search results from history and suggest the first result
                if let Some(suggestion) = self.suggester.suggest(states) {
                    let trimmed_selection = suggestion[res.len()..].to_string();
                    styled_buf.push(
                        trimmed_selection.as_str(),
                        states.get::<Theme>().suggestion_style,
                    );
                }
            }

            self.painter
                .paint(states, &self.prompt, &self.menu, &styled_buf)?;
            if auto_run {
                self.buffer_history.clear();
                self.painter.newline()?;
                break;
            }

            let event = read()?;

            if let Event::Key(key_event) = event {
                if sh.keybinding.handle_key_event(states, key_event) {
                    break;
                }
            }

            let should_break = self.handle_standard_keys(sh, states, event.clone())?;
            if should_break {
                break;
            }

            // handle menu events
            if self.menu.is_active() {
                self.handle_menu_keys(sh, states, event.clone())?;
            } else {
                if states.line().mode == LineMode::Insert {
                    self.handle_insert_keys(sh, states, event)?;
                } else if states.line().mode == LineMode::Normal {
                    self.handle_normal_keys(sh, states, event)?;
                }
            }
        }

        let res = states.line().get_full_command();
        if !res.is_empty() {
            states.get_mut::<Box<dyn History>>().add(res.clone());
        }
        Ok(res)
    }

    fn handle_menu_keys(
        &mut self,
        sh: &Shell,
        states: &States,
        event: Event,
    ) -> anyhow::Result<()> {
        match event {
            Event::Key(KeyEvent {
                code: KeyCode::Enter,
                modifiers: KeyModifiers::NONE,
                ..
            }) => {
                if let Some(accepted) = self.menu.accept().cloned() {
                    self.accept_completion(states, accepted)?;
                }
            },
            Event::Key(KeyEvent {
                code: KeyCode::Esc,
                modifiers: KeyModifiers::NONE,
                ..
            }) => {
                self.menu.disactivate();
            },
            Event::Key(KeyEvent {
                code: KeyCode::Tab,
                modifiers: KeyModifiers::SHIFT,
                ..
            })
            | Event::Key(KeyEvent {
                code: KeyCode::Up,
                modifiers: KeyModifiers::NONE,
                ..
            }) => {
                self.menu.previous();
            },
            Event::Key(KeyEvent {
                code: KeyCode::Tab,
                modifiers: KeyModifiers::NONE,
                ..
            })
            | Event::Key(KeyEvent {
                code: KeyCode::Down,
                modifiers: KeyModifiers::NONE,
                ..
            }) => {
                self.menu.next();
            },
            _ => {
                self.menu.disactivate();
                match states.line().mode {
                    LineMode::Insert => {
                        self.handle_insert_keys(sh, states, event)?;
                    },
                    LineMode::Normal => {
                        self.handle_normal_keys(sh, states, event)?;
                    },
                };
            },
        };
        Ok(())
    }

    //Keys that are universal regardless of mode, ex. Enter, Ctrl-c
    fn handle_standard_keys(
        &mut self,
        sh: &Shell,
        states: &States,
        event: Event,
    ) -> anyhow::Result<bool> {
        match event {
            Event::Resize(a, b) => {
                self.painter.set_term_size(a, b);
            },
            Event::Paste(p) => {
                states.line().cb.insert(Location::Cursor(), p.as_str())?;
            },
            Event::Key(KeyEvent {
                code: KeyCode::Char('c'),
                modifiers: KeyModifiers::CONTROL,
                ..
            }) => {
                states.line().cb.clear();
                self.buffer_history.clear();
                states.line().lines = String::new();
                self.painter.newline()?;

                return Ok(true);
            },
            // Insert suggestion when right arrow
            Event::Key(KeyEvent {
                code: KeyCode::Right,
                modifiers: KeyModifiers::NONE,
                ..
            }) => {
                if let Some(suggestion) = self.suggester.suggest(states) {
                    states.line().cb.clear();
                    states
                        .line()
                        .cb
                        .insert(Location::Cursor(), suggestion.as_str())?;
                }
            },

            Event::Key(KeyEvent {
                code: KeyCode::Enter,
                modifiers: KeyModifiers::NONE,
                ..
            })
            | Event::Key(KeyEvent {
                code: KeyCode::Char('j'),
                modifiers: KeyModifiers::CONTROL,
                ..
            }) => {
                if self.menu.is_active() {
                    return Ok(false);
                }
                self.buffer_history.clear();
                self.painter.newline()?;

                if sh.lang.needs_line_check(sh, states) {
                    states.line().lines += states.line().cb.as_str().into_owned().as_str();
                    states.line().lines += "\n";
                    states.line().cb.clear();

                    return Ok(false);
                }

                return Ok(true);
            },
            Event::Key(KeyEvent {
                code: KeyCode::Char('d'),
                modifiers: KeyModifiers::CONTROL,
                ..
            }) => {
                // if current input is empty exit the shell, otherwise treat it as enter
                if states.line().cb.is_empty() {
                    // TODO maybe unify exiting the shell
                    let _ = disable_raw_mode(); // TODO this is temp fix, should be more graceful way of
                                                // handling cleanup code
                    std::process::exit(0);
                } else {
                    self.buffer_history.clear();
                    self.painter.newline()?;
                    return Ok(true);
                }
            },

            _ => (),
        };

        Ok(false)
    }
    /// returns a bool whether input should still be handled
    pub fn expand(&mut self, states: &States, event: &Event) -> anyhow::Result<bool> {
        if !self.snippets.should_expand(event) {
            return Ok(true);
        }
        //find current word

        let cur_line = states.line().cb.as_str().to_string();
        let mut words = cur_line.split(' ').collect::<Vec<_>>();
        let mut char_offset = 0;
        //cursor is positioned just after the last typed character
        let index_before_cursor = states.line().cb.cursor();
        let mut cur_word_index = None;
        for (i, word) in words.iter().enumerate() {
            // Determine the start and end indices of the current word
            let start_index = char_offset;
            let end_index = char_offset + word.len();

            // Check if the cursor index falls within the current word
            if index_before_cursor >= start_index && index_before_cursor <= end_index {
                cur_word_index = Some(i);
            }

            // Update the character offset to account for the current word and whitespace
            char_offset = end_index + 1; // Add 1 for the space between words
        }

        if let Some(c) = cur_word_index {
            if let Some(expanded) = self.snippets.get(&words[c].to_string()) {
                //check if we're we're expanding the first word
                if expanded.position == Position::Command {
                    if c != 0 {
                        return Ok(true);
                    }
                }
                words[c] = expanded.value.as_str();

                states.line().cb.clear();
                //cursor automatically positioned at end
                states
                    .line()
                    .cb
                    .insert(Location::Cursor(), words.join(" ").as_str())?;
                return Ok(false);
            }
        }
        return Ok(true);
    }

    fn handle_insert_keys(
        &mut self,
        sh: &Shell,
        states: &States,
        event: Event,
    ) -> anyhow::Result<()> {
        if !self.expand(states, &event)? {
            return Ok(());
        }

        match event {
            Event::Key(KeyEvent {
                code: KeyCode::Tab,
                modifiers: KeyModifiers::NONE,
                ..
            }) => {
                self.populate_completions(states)?;
                self.menu.activate();

                let completion_len = self.menu.items().len();

                // no-op if no completions
                if completion_len == 0 {
                    self.menu.disactivate();
                    return Ok(());
                }
                // if completions only has one entry, automatically select it
                if completion_len == 1 {
                    // TODO stupid ownership stuff
                    let item = self.menu.items().get(0).map(|x| (*x).clone()).unwrap();
                    self.accept_completion(states, item.1)?;
                    self.menu.disactivate();
                    return Ok(());
                }

                // TODO make this feature toggable
                // TODO this is broken
                // Automatically accept the common prefix
                /*
                let completions: Vec<&str> = self
                    .menu
                    .items()
                    .iter()
                    .map(|(preview, _)| preview.as_str())
                    .collect();
                let prefix = longest_common_prefix(completions);
                self.accept_completion(
                    states,
                    Completion {
                        add_space: false,
                        display: None,
                        completion: prefix.clone(),
                        replace_method: ReplaceMethod::Append,
                    },
                )?;

                // recompute completions with prefix stripped
                // TODO this code is horrifying
                let items = self.menu.items();
                let new_items = items
                    .iter()
                    .map(|(preview, complete)| {
                        let mut complete = complete.clone();
                        complete.completion = complete.completion[prefix.len()..].to_string();
                        (preview.clone(), complete)
                    })
                    .collect();
                self.menu.set_items(new_items);
                */

                self.menu.activate();
            },
            Event::Key(KeyEvent {
                code: KeyCode::Left,
                modifiers: KeyModifiers::NONE,
                ..
            }) => {
                if states.line().cb.cursor() > 0 {
                    states.line().cb.move_cursor(Location::Before())?;
                }
            },
            Event::Key(KeyEvent {
                code: KeyCode::Right,
                modifiers: KeyModifiers::NONE,
                ..
            }) => {
                if states.line().cb.cursor() < states.line().cb.len() {
                    states.line().cb.move_cursor(Location::After())?;
                }
            },
            Event::Key(KeyEvent {
                code: KeyCode::Down,
                modifiers: KeyModifiers::NONE,
                ..
            }) => {
                self.history_down(states)?;
            },
            Event::Key(KeyEvent {
                code: KeyCode::Up,
                modifiers: KeyModifiers::NONE,
                ..
            }) => {
                self.history_up(states)?;
            },
            Event::Key(KeyEvent {
                code: KeyCode::Esc, ..
            }) => {
                self.to_normal_mode(sh, states)?;
                self.buffer_history.add(&states.line().cb);
            },
            Event::Key(KeyEvent {
                code: KeyCode::Backspace,
                modifiers: KeyModifiers::NONE,
                ..
            })
            | Event::Key(KeyEvent {
                code: KeyCode::Char('h'),
                modifiers: KeyModifiers::CONTROL,
                ..
            }) => {
                if !states.line().cb.is_empty() && states.line().cb.cursor() != 0 {
                    states
                        .line()
                        .cb
                        .delete(Location::Before(), Location::Cursor())?;
                }
            },
            Event::Key(KeyEvent {
                code: KeyCode::Char('w'),
                modifiers: KeyModifiers::CONTROL,
                ..
            }) => {
                if !states.line().cb.is_empty() && states.line().cb.cursor() != 0 {
                    let start = states.line().cb.motion_to_loc(Motion::BackWord)?;
                    states.line().cb.delete(start, Location::Cursor())?;
                }
            },

            Event::Key(KeyEvent {
                code: KeyCode::Char('a'),
                modifiers: KeyModifiers::CONTROL,
                ..
            }) => {
                states.line().cb.move_cursor(Location::Front())?;
            },

            Event::Key(KeyEvent {
                code: KeyCode::Char('e'),
                modifiers: KeyModifiers::CONTROL,
                ..
            }) => {
                states
                    .line()
                    .cb
                    .move_cursor(Location::Back(&states.line().cb))?;
            },

            Event::Key(KeyEvent {
                code: KeyCode::Char(c),
                ..
            }) => {
                states
                    .line()
                    .cb
                    .insert(Location::Cursor(), &c.to_string())?;
            },
            _ => {},
        };
        Ok(())
    }

    fn handle_normal_keys(
        &mut self,
        sh: &Shell,
        states: &States,
        event: Event,
    ) -> anyhow::Result<()> {
        // TODO write better system toString support key combinations
        match event {
            Event::Key(KeyEvent {
                code: KeyCode::Esc, ..
            }) => {
                self.normal_keys.clear();
            },
            Event::Key(KeyEvent {
                code: KeyCode::Char(c),
                ..
            }) => {
                self.normal_keys.push(c);

                if let Ok(Command { repeat, action }) = Parser::default().parse(&self.normal_keys) {
                    for _ in 0..repeat {
                        // special cases (possibly consulidate with execute_vi somehow)

                        if let Ok(mode) = states.line().cb.execute_vi(action.clone()) {
                            if mode != states.line().mode {
                                match mode {
                                    LineMode::Insert => self.to_insert_mode(sh, states)?,
                                    LineMode::Normal => self.to_normal_mode(sh, states)?,
                                };
                            }
                        }
                        match action {
                            Action::Undo => self.buffer_history.prev(states.line().cb.borrow_mut()),

                            Action::Redo => self.buffer_history.next(states.line().cb.borrow_mut()),
                            Action::Move(motion) => match motion {
                                Motion::Up => self.history_up(states)?,
                                Motion::Down => self.history_down(states)?,
                                _ => {},
                            },
                            Action::Editor => {
                                // TODO should this just use the env var? or should shrs have
                                // dedicated config?

                                // If EDITOR command is not set just display some sort of warning
                                // and move on
                                let Ok(editor) = std::env::var("EDITOR") else {
                                    return Ok(());
                                };

                                let mut tempbuf = tempfile::NamedTempFile::new().unwrap();

                                // write contexts of line to file
                                tempbuf
                                    .write_all(states.line().cb.as_str().as_bytes())
                                    .unwrap();

                                // TODO should use shrs_job for this?
                                // TODO configure the command used
                                let mut child = std::process::Command::new(editor)
                                    .arg(tempbuf.path())
                                    .spawn()
                                    .unwrap();

                                child.wait().unwrap();

                                // read update file contexts back to line
                                let mut new_contents = String::new();
                                tempbuf.rewind().unwrap();
                                tempbuf.read_to_string(&mut new_contents).unwrap();

                                // strip last newline
                                // TODO this is very platform and editor dependent
                                let trimmed = new_contents.trim_end_matches("\n");

                                states.line().cb.clear();
                                states
                                    .line()
                                    .cb
                                    .insert(Location::Cursor(), trimmed)
                                    .unwrap();

                                // TODO should auto run the command?

                                tempbuf.close().unwrap();
                            },
                            _ => {
                                self.buffer_history.add(&states.line().cb);
                            },
                        }
                    }

                    self.normal_keys.clear();
                }
            },
            _ => {},
        }
        Ok(())
    }

    // recalculate the current completions
    fn populate_completions(&mut self, states: &States) -> anyhow::Result<()> {
        // TODO IFS
        let c = states.line();
        let args =
            c.cb.slice(..states.line().cb.cursor())
                .clone()
                .as_str()
                .unwrap()
                .split(' ');
        states.line().current_word = args.clone().last().unwrap_or("").to_string();

        let comp_states = CompletionCtx::new(args.map(|s| s.to_owned()).collect::<Vec<_>>());

        let completions = states.get::<Box<dyn Completer>>().complete(&comp_states);
        let completions = completions.iter().collect::<Vec<_>>();

        let menuitems = completions
            .iter()
            .map(|c| (c.display(), (*c).clone()))
            .collect::<Vec<_>>();
        self.menu.set_items(menuitems);

        Ok(())
    }

    // replace word at cursor with accepted word (used in automcompletion)
    fn accept_completion(&mut self, states: &States, completion: Completion) -> anyhow::Result<()> {
        // first remove current word
        // TODO could implement a delete_before
        // TODO make use of ReplaceMethod
        match completion.replace_method {
            ReplaceMethod::Append => {
                // no-op
            },
            ReplaceMethod::Replace => {
                states
                    .line()
                    .cb
                    .move_cursor(Location::Rel(-(states.line().current_word.len() as isize)))?;
                let cur_word_len =
                    unicode_width::UnicodeWidthStr::width(states.line().current_word.as_str());
                states
                    .line()
                    .cb
                    .delete(Location::Cursor(), Location::Rel(cur_word_len as isize))?;
                states.line().current_word.clear();
            },
        }

        // then replace with the completion word
        states
            .line()
            .cb
            .insert(Location::Cursor(), &completion.accept())?;

        Ok(())
    }

    fn history_up(&mut self, states: &States) -> anyhow::Result<()> {
        // save current prompt
        if HistoryInd::Prompt == states.line().history_ind {
            states.line().saved_line = states.line().cb.slice(..).to_string();
        }

        states.line().history_ind = states
            .line()
            .history_ind
            .up(states.get::<Box<dyn History>>().len());
        self.update_history(states)?;

        Ok(())
    }

    fn history_down(&mut self, states: &States) -> anyhow::Result<()> {
        states.line().history_ind = states.line().history_ind.down();
        self.update_history(states)?;

        Ok(())
    }

    fn update_history(&mut self, states: &States) -> anyhow::Result<()> {
        match states.line().history_ind {
            // restore saved line
            HistoryInd::Prompt => {
                states.line().cb.clear();
                states
                    .line()
                    .cb
                    .insert(Location::Cursor(), &states.line().saved_line)?;
            },
            // fill prompt with history element
            HistoryInd::Line(i) => {
                let h = states.get::<Box<dyn History>>();
                let history_item = h.get(i).unwrap();
                states.line().cb.clear();
                states.line().cb.insert(Location::Cursor(), history_item)?;
            },
        }
        Ok(())
    }

    fn to_normal_mode(&self, sh: &Shell, states: &States) -> anyhow::Result<()> {
        states.line().mode = LineMode::Normal;

        let hook_states = LineModeSwitchCtx {
            line_mode: LineMode::Normal,
        };
        sh.hooks.run(sh, states, hook_states)?;
        Ok(())
    }

    fn to_insert_mode(&self, sh: &Shell, states: &States) -> anyhow::Result<()> {
        states.line().mode = LineMode::Insert;

        let hook_states = LineModeSwitchCtx {
            line_mode: LineMode::Insert,
        };
        sh.hooks.run(sh, states, hook_states)?;
        Ok(())
    }
}
