#!/bin/bash

crates=(
    shrs_job
    shrs_utils
    shrs_core
    shrs_lang
    shrs_vi
    shrs
)
plugins=(
    # shrs_analytics
    shrs_autocd
    shrs_cd_stack
    shrs_cd_tools
    shrs_command_timer
    shrs_completion
    shrs_derive_completion
    shrs_file_history
    shrs_file_logger
    shrs_manpages
    shrs_mux
    shrs_output_capture
    shrs_rhai
    shrs_rhai_completion
    shrs_run_context
)

for crate in "${crates[@]}"; do
    echo "Publishing $crate"
    cargo publish -p $crate
done

for plugin in "${plugins[@]}"; do
    echo "Publishing $plugin"
    cargo publish -p $plugin
done

#cargo smart-release -d keep --update-crates-index --no-changelog --no-tag "${crates[@]}" "${plugins[@]}"
